name: verify and publish javadoc on gh-pages

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
      PASSPHRASE: ${{ secrets.PASSPHRASE }}
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      BINANCE_API_KEY: ${{ secrets.BINANCE_API_KEY }}
      BINANCE_API_SECRET: ${{ secrets.BINANCE_API_SECRET }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v1
      - name: configure settings
        uses: s4u/maven-settings-action@v2.6.0
        with:
          servers: '[{"id": "ossrh", "username": "${{ env.OSSRH_USERNAME }}", "password": "${{ env.OSSRH_PASSWORD }}"}]'
      - name: deploy maven artifact
        run: |
          mvn \
          --no-transfer-progress \
          --batch-mode \
          -Dgpg.passphrase=${{ env.PASSPHRASE }} \
          clean deploy 
      - name: Deploy javadoc to gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          BRANCH: gh-pages
          CLEAN: true
          FOLDER: target/apidocs
          TARGET_FOLDER: /